version: "3"

services:
  hub:
    image: selenium/hub:latest
    ports:
      - "4444:4444"
    environment:
      - GRID_BROWSER_TIMEOUT=120
      - GRID_TIMEOUT=120
      - GRID_NEW_SESSION_WAIT_TIMEOUT=120
      - GRID_MAX_SESSION=10

  chrome:
    image: selenium/node-chrome-debug:latest
    ports:
      - "5900"
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub

  firefox:
    image: selenium/node-firefox-debug:latest
    ports:
      - "5901"
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub

  novnc:
    image: dorowu/ubuntu-desktop-lxde-vnc
    ports:
      - "6080:80"
    depends_on:
      - chrome
      - firefox
    environment:
      - VNC_PASSWORD=secret
      - RESOLUTION=1280x1024
