trigger:
  tags:
    include:
    - v*

jobs:
- job: build_and_release_genymotion_and_device
  pool:
    vmImage: ubuntu-20.04
  strategy:
    maxParallel: 2
    matrix:
      genymotion:
        script.name: './release_real.sh'
      real_device:
        script.name: './release_geny.sh'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.8.12'
      displayName: 'Use Python 3.8.12'

  - script: |
      latest_tag=$(git describe --tags --abbrev=0)
      echo "##vso[task.setvariable variable=release_version]$latest_tag"

    displayName: 'Get the latest release tag'

  - script: |
      docker login -u $(DOCKER_USERNAME) -p=$(DOCKER_PASSWORD)
      $(script.name) all $(release_version)
      docker logout

    displayName: 'Build docker image, run unit tests and push the docker image'

  - script: bash <(curl -s https://codecov.io/bash)
    displayName: 'Publish test result'
