trigger:
  tags:
    include:
    - v*

jobs:
- job: build_and_release_emulators
  pool:
    vmImage: ubuntu-20.04
  strategy:
    maxParallel: 10
    matrix:
      6.0:
        android.version: '6.0'
      7.0:
        android.version: '7.0'
      7.1.1:
        android.version: '7.1.1'
      8.0:
        android.version: '8.0'
      8.1:
        android.version: '8.1'
      9.0:
        android.version: '9.0'
      10.0:
        android.version: '10.0'
      11.0:
        android.version: '11.0'
      12.0:
        android.version: '12.0'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.8.12'
      displayName: 'Use Python 3.8.12'

  - script: |
      latest_tag=$(git describe --tags --abbrev=0)
      echo "##vso[task.setvariable variable=release_version]$latest_tag"

    displayName: 'Get the latest release tag'

  - script: |
      docker login -u $(DOCKER_USERNAME) -p=$(DOCKER_PASSWORD)
      ./release.sh all $(android.version) $(release_version)
      docker logout

    displayName: 'Build docker image, run unit tests and push the docker image'

  - script: bash <(curl -s https://codecov.io/bash)
    displayName: 'Publish test result'
