# Usage: docker-compose up -d
version: "3"

services:
  svc:
    image: sample-docker:latest
    privileged: true  # for usb connection 
    volumes:
      - ./tests:/root/tests
      - /dev/shm:/dev/shm        
      - /dev/bus/usb:/dev/bus/usb
    ports:
      - "5901:5901"
    stop_grace_period: 5s
