version: "3.9"
services:
  api:
    build: .
    ports:
      - "3000:3000"
    command: npm start
    environment:
      NODE_ENV: test
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: myapp_test