version: '3.8'

services:
  db:
    image: mysql
    environment:
      - MYSQL_DB=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
      - MYSQL_INITDB_ARGS=--encoding=UTF-8

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=test
      - DB_USERNAME=test
      - DB_PASSWORD=test
    depends_on:
      - db
    ports:
      - "3000:3000"
    command:
      - bash
      - -c
      - |
        /app/wait-for-it.sh db:3306 -t 10
        npm run start
    volumes:
      - ./:/app/