version: '3'

services:
  jenkins:
    image: hcmoon92/devops:jenkins-v0.2  # v0.2 : jenkin plug installed version
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    user: "1000:1000"      
    volumes:
      - ../jenkins_home:/var/jenkins_home
