version: '3.9'
services:
  gitlab-runner:
    image: 'gitlab/gitlab-runner:v14.6.1'
    container_name: gitlab-runner
    restart: always
    volumes:
      - './config:/etc/gitlab-runner'
      - '/var/run/docker.sock:/var/run/docker.sock'