apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../kompose.yml
    kompose.version: 1.1.0 (36652f6)
  creationTimestamp: null
  labels:
    io.kompose.service: nexus-7.1.1
  name: nexus-7.1.1
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: nexus-7.1.1
    spec:
      containers:
      - env:
        - name: APPIUM
          value: "true"
        - name: AUTO_RECORD
          value: "true"
        - name: CONNECT_TO_GRID
          value: "true"
        - name: DEVICE
          value: Nexus 5
        - name: SELENIUM_HOST
          value: selenium_hub
        image: butomo1989/docker-android-x86-7.1.1
        name: nexus-7.1.1
        ports:
        - containerPort: 6080
        resources: {}
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /root/tmp/sample_apk
          name: nexus-7.1.1-claim0
        - mountPath: /tmp/video
          name: nexus-7.1.1-claim1
      restartPolicy: Always
      volumes:
      - name: nexus-7.1.1-claim0
        persistentVolumeClaim:
          claimName: nexus-7.1.1-claim0
      - name: nexus-7.1.1-claim1
        persistentVolumeClaim:
          claimName: nexus-7.1.1-claim1
status: {}
