version: "3"
services:
  novnc:
    image: hcmoon92/devops:ubuntu-desktop-lxde-vnc-focal-v0.1
    environment:
      - USER=henry
      #- VNC_PASSWORD=tta123!@
    ports:
      - "6080:80"
      - "5900:5900"
    volumes:
      - ./:/app
      - /dev/shm:/dev/shm