version: '3'

services:
  cypress:
    image: cypress/browsers:latest
    environment:
      - CYPRESS_baseUrl=http://localhost:8080
    volumes:
      - ./e2e:/e2e
    ports:
      - "5901:5901"
      - "6901:6901"