version: '3'

services:
  web:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: '192.168.56.101'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://192.168.56.101:8929'
    ports:
      - '8929:8929'
      - '8922:22'
    volumes:
      - './data/gitlab/config:/etc/gitlab'
      - './data/gitlab/logs:/var/log/gitlab'
      - './data/gitlab/data:/var/opt/gitlab'
