# Usage: docker-compose up -d
version: "3"

services:
  android-sdk:
    images: hcmoon92/devops:android-sdk-v0.9
    ports:
      - "2222:22"
#    volumes:
#      - ./tests:/root/tests
  android-sdk-vnc:
    images: hcmoon92/devops:android-sdk-vnc-v0.9
    ports:
      - "5901:5901"
#    volumes:
#      - ./tests:/root/tests
