version: '3'
services:
  webapp:
    build: ./webapp
    ports:
      - "8080:8080"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=database
  mysql:
    build: ./mysql
    ports:
      - "3306:3306"
  tests:
    build: ./tests
    environment:
      - APP_HOST=app
      - APP_PORT=8080
      - MYSQL_HOST=mysql
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=database
    volumes:
      - .:/app
