version: '3'

services:
  jenkins:
    image: hcmoon92/devops:jenkins-docker-v0.3  
    # v0.3 : jenkins plug installed version + docker + docker-compose
    container_name: jenkins-docker
    privileged: true
    ports:
      - "80:8080"
      - "50000:50000"
    volumes:
      - ../jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
