version: '3.9'

services:
  jenkins:
    image: hcmoon92/devops:jenkins-docker-sample-v0.5  
    # v0.3 : jenkins plug installed version + docker + docker-compose
    # v0.5 : jenkins freestyle example 
    container_name: jenkins-docker
    privileged: true
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      TZ: "Asia/Seoul"
    volumes:
      - ../jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
