version: '3.2'

services:
   db:
      image: mysql:8.0
      container_name: my_db
      restart: always
      ports:
       - '3306:3306'
      environment:
        MYSQL_DATABASE: my_database
        MYSQL_USER: henry
        MYSQL_PASSWORD: tta123!@
        MYSQL_ROOT_PASSWORD: tta123!@      

   app:
      depends_on:
       - db
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      restart: always
      ports:
       - '8080:80'
      environment:
        PMA_HOST: db
