version: "3"
services:
  appium:
    image: appium/appium:1.20.2
    ports:
      - "4723:4723"
    environment:
      - NODE_CONFIG={
          "port":4723,
          "cleanUpCycle":2000,
          "timeout":30000,
          "proxy":"false",
          "maxInstances":1,
          "register":true,
          "registerCycle":5000,
          "hubPort":4444,
          "hubHost":"selenium-hub"
        }
    depends_on:
      - selenium-hub
    networks:
      - appium-network
  selenium-hub:
    image: selenium/hub:3.141.59-20210825
    ports:
      - "4444:4444"
    networks:
      - appium-network
  chrome:
    image: selenium/node-chrome:3.141.59-20210825
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
    networks:
      - appium-network
networks:
  appium-network:
    driver: bridge
