# Usage: docker-compose up -d
version: "3"

services:
  android-sdk-vnc-studio:
    image: hcmoon92/devops:android-sdk-vnc-studio-v0.92
    ports:
      - "5901:5901"
#    volumes:
#      - ./tests:/root/tests
