---
version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
    commit-message:
    # Prefix all commit messages with "npm"
    prefix: 'npm'
    # Specify labels for npm pull requests
    labels:
      - 'npm'
      - 'dependencies'
    # Set to 0 to disable version updates
    open-pull-requests-limit: 2
