apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../kompose.yml
    kompose.version: 1.1.0 (36652f6)
  creationTimestamp: null
  labels:
    io.kompose.service: samsung-galaxy-web-5.1.1
  name: samsung-galaxy-web-5.1.1
spec:
  ports:
  - name: "6080"
    port: 6080
    targetPort: 6080
  selector:
    io.kompose.service: samsung-galaxy-web-5.1.1
status:
  loadBalancer: {}
