version: "3.8"
services:
  desktop-novnc-rf:
    image: hcmoon92/devops:desktop-lxde-vnc-rf-v0.1	
    # python, node10, robotframework
    environment:
      - USER=henry
      #- VNC_PASSWORD=tta123!@
    ports:
      - "6080:80"
      - "5900:5900"
    volumes:
      - ./:/app
      - /dev/shm:/dev/shm   

   mysql:
      image: mysql:8.0
      container_name: my_db
      restart: always
      ports:
       - '3306:3306'
      environment:
        MYSQL_DATABASE: my_database
        MYSQL_USER: henry
        MYSQL_PASSWORD: tta123!@
        MYSQL_ROOT_PASSWORD: tta123!@      

   phpmyadmin:
      depends_on:
       - mysql
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      restart: always
      ports:
       - '8080:80'
      environment:
        PMA_HOST: mysql
