version: '3'

services:
  web:
    image: 'hcmoon92/devops:gitlab-v0.1'
    restart: always
    hostname: '192.168.56.101'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://192.168.56.101:8929'
      GITLAB_ROOT_PASSWORD: tta123!@
      GITLAB_TIMEZONE: Asia/Seoul            
    ports:
      - '8929:8929'
      - '8922:22'

#    volumes:
#      - './data/gitlab/config:/etc/gitlab'
#      - './data/gitlab/logs:/var/log/gitlab'
#      - './data/gitlab/data:/var/opt/gitlab'
